name: Publish to nuget
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            3.1.x
            6.0.x
      - name: Restore
        run: dotnet restore src/MediatR.BackgroundService/MediatR.BackgroundService.sln
      - name: Build
        run: dotnet build src/MediatR.BackgroundService/MediatR.BackgroundService.sln --configuration Release --no-restore
      - name: Package
        run: dotnet pack src/MediatR.BackgroundService/MediatR.BackgroundService/MediatR.BackgroundService.csproj
      - name: Publish
        run: dotnet nuget push src/MediatR.BackgroundService/MediatR.BackgroundService/bin/Release/netcoreapp3.1/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      # - name: Publish
      #   uses: rohith/publish-nuget@v2
      #   with:
      #     PROJECT_FILE_PATH: src/MediatR.BackgroundService/MediatR.BackgroundService/MediatR.BackgroundService.csproj
      #     NUGET_KEY: ${{secrets.NUGET_API_KEY}}