name: Publish to nuget
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
      - name: Restore
        run: dotnet restore MediatR.BackgroundService.sln
      - name: Build
        run: dotnet build MediatR.BackgroundService.sln --configuration Release --no-restore
      - name: Package
        run: dotnet pack src/MediatR.BackgroundService/MediatR.BackgroundService.csproj --configuration Release
      - name: Publish
        run: dotnet nuget push src/MediatR.BackgroundService/bin/Release/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}